modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
issueTrackerURL="https://github.com/Franchino961-Mod/AE2-Draconic-Fusion-Autocrafter/issues"

[[mods]]
modId="ae2_draconic_fusion_autocrafter"
version="${mod_version}"
displayName="AE2 Draconic Fusion Autocrafter"
logoFile="assets/ae2_draconic_fusion_autocrafter/icon.png"
displayURL="https://www.curseforge.com/minecraft/mc-mods/ae2-draconic-fusion-autocrafter"
displayTest="MATCH_VERSION"
authors="Franchino961"
description='''
AE2 addon for automating Draconic Evolution Fusion Crafting through core-only connection.
'''

[[dependencies.ae2_draconic_fusion_autocrafter]]
modId="neoforge"
type="required"
versionRange="[21.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.ae2_draconic_fusion_autocrafter]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.ae2_draconic_fusion_autocrafter]]
modId="ae2"
type="required"
versionRange="[19.2.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.ae2_draconic_fusion_autocrafter]]
modId="draconicevolution"
type="required"
versionRange="[3.1.4.630,)"
ordering="AFTER"
side="BOTH"
